
services:
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/index_data
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - chroma
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chroma:8000
volumes:
  chroma-data:
  ollama-data: